# Wiki RAG Application Configuration

# Service URLs
elasticsearch:
  url: "http://localhost:9200"
  docker_url: "http://elasticsearch:9200"
  index: "medical_docs"
  request_timeout: 100
  max_retries: 5
  retry_on_timeout: true
  http_compress: true

qdrant:
  url: "http://localhost:6333"
  docker_url: "http://qdrant:6333"
  collection: "medical_rag_sparse"
  timeout: 30
  prefer_grpc: false

# Model configurations
models:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  vector_dims: 384
  normalize_embeddings: true
  openai_model: "gpt-4o-mini"
  temperature: 0.1
  max_tokens: 500

# Search parameters
search:
  default_top_k: 5
  eval_top_k: 2
  batch_size: 32
  large_batch_size: 512
  min_content_length: 100

# RRF (Reciprocal Rank Fusion) parameters
rrf:
  k: 60
  weights: [2.0, 1.0]  # [semantic_weight, bm25_weight]

# Application control flags
app:
  skip_warmup: false
  prefix_ids: false

# Data paths and processing
data:
  base_dir: "data"
  dataset_paths:
    textbook: "MedRAG/textbooks"
    pubmed: "MedRAG/pubmed"
    wiki: "data/medical_wiki"
  output_format: "json"

# Seed generation configurations
seeds:
  small:
    medical_textbook:
      size: 2000
      max_size: 125847
    medical_pubmed:
      size: 20000
      max_size: 2000000
    medical_wiki:
      size: 2000
      max_size: null
  medium:
    medical_textbook:
      size: 60000
      max_size: 125847
    medical_pubmed:
      size: 600000
      max_size: 2000000
    medical_wiki:
      size: 60000
      max_size: null

# Elasticsearch index settings
index_settings:
  settings:
    number_of_shards: 1
    number_of_replicas: 0
  mappings:
    properties:
      id:
        type: "keyword"
      source_type:
        type: "keyword"
      title:
        type: "text"
        analyzer: "english"
      text:
        type: "text"
        analyzer: "english"
      wiki_id:
        type: "keyword"
      source:
        type: "keyword"
      url:
        type: "keyword"
      text_vector:
        type: "dense_vector"
        dims: 384
        index: true
        similarity: "cosine"

# Evaluation settings
evaluation:
  ground_truth_path: "data/evaluation/ground_truth.json"

# Streamlit app settings
streamlit:
  title: "Medical RAG System"
  sidebar_title: "Search Options"
  default_image: "app/images/54316015-blood-pressure-health-check.jpg"

# Java/Elasticsearch JVM settings
java:
  heap_min: "1g"
  heap_max: "1g"

# Environment variables mapping
env_vars:
  - "OPENAI_API_KEY"
  - "ES_URL"
  - "QDRANT_URL"
  - "ES_INDEX"
  - "QDRANT_COLLECTION"
  - "SKIP_WARMUP"
  - "OPENAI_MODEL"
  - "ENVIRONMENT"
